name: CI_MLflow_Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Set up job
        run: echo "Starting CI job..."

      - name: 🧩 Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: 🔍 Check Env
        run: |
          echo "Python version:"
          python --version
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -R .

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==2.16.2 joblib scikit-learn pandas numpy matplotlib
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: 🔧 Set MLflow Tracking URI
        run: |
          echo "Setting MLflow Tracking URI..."
          export MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}

      - name: 🧪 Run mlflow project (train model)
        run: |
          cd MLProject
          python modelling.py 100 10  # Menjalankan training model dengan parameter default
          echo "✅ MLflow project completed."
          ls -R .

      - name: 📤 Upload to Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          cd MLProject
          python gdrive.py
          echo "✅ Upload to Google Drive selesai."

      - name: 🧩 Post Set up Python 3.12.7
        run: echo "Post Python setup completed."

      - name: 🧩 Post Run actions/checkout@v3
        run: echo "Post checkout completed."

      - name: ✅ Complete job
        run: echo "Workflow CI selesai dengan sukses!"
